# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/WDBlack2/CLionProjects/Ragger

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/WDBlack2/CLionProjects/Ragger

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cpack --config ./CPackSourceConfig.cmake /Volumes/WDBlack2/CLionProjects/Ragger/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"msgpack-cxx\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/WDBlack2/CLionProjects/Ragger/CMakeFiles /Volumes/WDBlack2/CLionProjects/Ragger//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/WDBlack2/CLionProjects/Ragger/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c_lib_po

# Build rule for target.
c_lib_po: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c_lib_po
.PHONY : c_lib_po

# fast build rule for target.
c_lib_po/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_lib_po.dir/build.make CMakeFiles/c_lib_po.dir/build
.PHONY : c_lib_po/fast

#=============================================================================
# Target rules for targets named ragger_core

# Build rule for target.
ragger_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ragger_core
.PHONY : ragger_core

# fast build rule for target.
ragger_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/build
.PHONY : ragger_core/fast

#=============================================================================
# Target rules for targets named ragger

# Build rule for target.
ragger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ragger
.PHONY : ragger

# fast build rule for target.
ragger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger.dir/build.make CMakeFiles/ragger.dir/build
.PHONY : ragger/fast

#=============================================================================
# Target rules for targets named tokenizers_cpp

# Build rule for target.
tokenizers_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tokenizers_cpp
.PHONY : tokenizers_cpp

# fast build rule for target.
tokenizers_cpp/fast:
	$(MAKE) $(MAKESILENT) -f vendor/tokenizers-cpp/CMakeFiles/tokenizers_cpp.dir/build.make vendor/tokenizers-cpp/CMakeFiles/tokenizers_cpp.dir/build
.PHONY : tokenizers_cpp/fast

#=============================================================================
# Target rules for targets named tokenizers_c

# Build rule for target.
tokenizers_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tokenizers_c
.PHONY : tokenizers_c

# fast build rule for target.
tokenizers_c/fast:
	$(MAKE) $(MAKESILENT) -f vendor/tokenizers-cpp/CMakeFiles/tokenizers_c.dir/build.make vendor/tokenizers-cpp/CMakeFiles/tokenizers_c.dir/build
.PHONY : tokenizers_c/fast

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doxygen
.PHONY : doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) $(MAKESILENT) -f vendor/tokenizers-cpp/msgpack/CMakeFiles/doxygen.dir/build.make vendor/tokenizers-cpp/msgpack/CMakeFiles/doxygen.dir/build
.PHONY : doxygen/fast

#=============================================================================
# Target rules for targets named sentencepiece-static

# Build rule for target.
sentencepiece-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sentencepiece-static
.PHONY : sentencepiece-static

# fast build rule for target.
sentencepiece-static/fast:
	$(MAKE) $(MAKESILENT) -f vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/sentencepiece-static.dir/build.make vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/sentencepiece-static.dir/build
.PHONY : sentencepiece-static/fast

#=============================================================================
# Target rules for targets named sentencepiece_train-static

# Build rule for target.
sentencepiece_train-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sentencepiece_train-static
.PHONY : sentencepiece_train-static

# fast build rule for target.
sentencepiece_train-static/fast:
	$(MAKE) $(MAKESILENT) -f vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/sentencepiece_train-static.dir/build.make vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/sentencepiece_train-static.dir/build
.PHONY : sentencepiece_train-static/fast

#=============================================================================
# Target rules for targets named spm_encode

# Build rule for target.
spm_encode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spm_encode
.PHONY : spm_encode

# fast build rule for target.
spm_encode/fast:
	$(MAKE) $(MAKESILENT) -f vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/spm_encode.dir/build.make vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/spm_encode.dir/build
.PHONY : spm_encode/fast

#=============================================================================
# Target rules for targets named spm_decode

# Build rule for target.
spm_decode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spm_decode
.PHONY : spm_decode

# fast build rule for target.
spm_decode/fast:
	$(MAKE) $(MAKESILENT) -f vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/spm_decode.dir/build.make vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/spm_decode.dir/build
.PHONY : spm_decode/fast

#=============================================================================
# Target rules for targets named spm_normalize

# Build rule for target.
spm_normalize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spm_normalize
.PHONY : spm_normalize

# fast build rule for target.
spm_normalize/fast:
	$(MAKE) $(MAKESILENT) -f vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/spm_normalize.dir/build.make vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/spm_normalize.dir/build
.PHONY : spm_normalize/fast

#=============================================================================
# Target rules for targets named spm_train

# Build rule for target.
spm_train: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spm_train
.PHONY : spm_train

# fast build rule for target.
spm_train/fast:
	$(MAKE) $(MAKESILENT) -f vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/spm_train.dir/build.make vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/spm_train.dir/build
.PHONY : spm_train/fast

#=============================================================================
# Target rules for targets named spm_export_vocab

# Build rule for target.
spm_export_vocab: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spm_export_vocab
.PHONY : spm_export_vocab

# fast build rule for target.
spm_export_vocab/fast:
	$(MAKE) $(MAKESILENT) -f vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/spm_export_vocab.dir/build.make vendor/tokenizers-cpp/sentencepiece/src/CMakeFiles/spm_export_vocab.dir/build
.PHONY : spm_export_vocab/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_config.dir/build.make tests/CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_bm25

# Build rule for target.
test_bm25: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bm25
.PHONY : test_bm25

# fast build rule for target.
test_bm25/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_bm25.dir/build.make tests/CMakeFiles/test_bm25.dir/build
.PHONY : test_bm25/fast

#=============================================================================
# Target rules for targets named test_sqlite_backend

# Build rule for target.
test_sqlite_backend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sqlite_backend
.PHONY : test_sqlite_backend

# fast build rule for target.
test_sqlite_backend/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_sqlite_backend.dir/build.make tests/CMakeFiles/test_sqlite_backend.dir/build
.PHONY : test_sqlite_backend/fast

#=============================================================================
# Target rules for targets named test_import

# Build rule for target.
test_import: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_import
.PHONY : test_import

# fast build rule for target.
test_import/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_import.dir/build.make tests/CMakeFiles/test_import.dir/build
.PHONY : test_import/fast

#=============================================================================
# Target rules for targets named test_auth

# Build rule for target.
test_auth: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_auth
.PHONY : test_auth

# fast build rule for target.
test_auth/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_auth.dir/build.make tests/CMakeFiles/test_auth.dir/build
.PHONY : test_auth/fast

#=============================================================================
# Target rules for targets named test_server

# Build rule for target.
test_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_server
.PHONY : test_server

# fast build rule for target.
test_server/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_server.dir/build.make tests/CMakeFiles/test_server.dir/build
.PHONY : test_server/fast

#=============================================================================
# Target rules for targets named test_client

# Build rule for target.
test_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_client
.PHONY : test_client

# fast build rule for target.
test_client/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_client.dir/build.make tests/CMakeFiles/test_client.dir/build
.PHONY : test_client/fast

ProgramOptions.o: ProgramOptions.cpp.o
.PHONY : ProgramOptions.o

# target to build an object file
ProgramOptions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_lib_po.dir/build.make CMakeFiles/c_lib_po.dir/ProgramOptions.cpp.o
.PHONY : ProgramOptions.cpp.o

ProgramOptions.i: ProgramOptions.cpp.i
.PHONY : ProgramOptions.i

# target to preprocess a source file
ProgramOptions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_lib_po.dir/build.make CMakeFiles/c_lib_po.dir/ProgramOptions.cpp.i
.PHONY : ProgramOptions.cpp.i

ProgramOptions.s: ProgramOptions.cpp.s
.PHONY : ProgramOptions.s

# target to generate assembly for a file
ProgramOptions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_lib_po.dir/build.make CMakeFiles/c_lib_po.dir/ProgramOptions.cpp.s
.PHONY : ProgramOptions.cpp.s

src/api_formats.o: src/api_formats.cpp.o
.PHONY : src/api_formats.o

# target to build an object file
src/api_formats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/api_formats.cpp.o
.PHONY : src/api_formats.cpp.o

src/api_formats.i: src/api_formats.cpp.i
.PHONY : src/api_formats.i

# target to preprocess a source file
src/api_formats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/api_formats.cpp.i
.PHONY : src/api_formats.cpp.i

src/api_formats.s: src/api_formats.cpp.s
.PHONY : src/api_formats.s

# target to generate assembly for a file
src/api_formats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/api_formats.cpp.s
.PHONY : src/api_formats.cpp.s

src/auth.o: src/auth.cpp.o
.PHONY : src/auth.o

# target to build an object file
src/auth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/auth.cpp.o
.PHONY : src/auth.cpp.o

src/auth.i: src/auth.cpp.i
.PHONY : src/auth.i

# target to preprocess a source file
src/auth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/auth.cpp.i
.PHONY : src/auth.cpp.i

src/auth.s: src/auth.cpp.s
.PHONY : src/auth.s

# target to generate assembly for a file
src/auth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/auth.cpp.s
.PHONY : src/auth.cpp.s

src/bm25.o: src/bm25.cpp.o
.PHONY : src/bm25.o

# target to build an object file
src/bm25.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/bm25.cpp.o
.PHONY : src/bm25.cpp.o

src/bm25.i: src/bm25.cpp.i
.PHONY : src/bm25.i

# target to preprocess a source file
src/bm25.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/bm25.cpp.i
.PHONY : src/bm25.cpp.i

src/bm25.s: src/bm25.cpp.s
.PHONY : src/bm25.s

# target to generate assembly for a file
src/bm25.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/bm25.cpp.s
.PHONY : src/bm25.cpp.s

src/chat.o: src/chat.cpp.o
.PHONY : src/chat.o

# target to build an object file
src/chat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/chat.cpp.o
.PHONY : src/chat.cpp.o

src/chat.i: src/chat.cpp.i
.PHONY : src/chat.i

# target to preprocess a source file
src/chat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/chat.cpp.i
.PHONY : src/chat.cpp.i

src/chat.s: src/chat.cpp.s
.PHONY : src/chat.s

# target to generate assembly for a file
src/chat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/chat.cpp.s
.PHONY : src/chat.cpp.s

src/client.o: src/client.cpp.o
.PHONY : src/client.o

# target to build an object file
src/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/client.cpp.o
.PHONY : src/client.cpp.o

src/client.i: src/client.cpp.i
.PHONY : src/client.i

# target to preprocess a source file
src/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/client.cpp.i
.PHONY : src/client.cpp.i

src/client.s: src/client.cpp.s
.PHONY : src/client.s

# target to generate assembly for a file
src/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/client.cpp.s
.PHONY : src/client.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/embedder.o: src/embedder.cpp.o
.PHONY : src/embedder.o

# target to build an object file
src/embedder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/embedder.cpp.o
.PHONY : src/embedder.cpp.o

src/embedder.i: src/embedder.cpp.i
.PHONY : src/embedder.i

# target to preprocess a source file
src/embedder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/embedder.cpp.i
.PHONY : src/embedder.cpp.i

src/embedder.s: src/embedder.cpp.s
.PHONY : src/embedder.s

# target to generate assembly for a file
src/embedder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/embedder.cpp.s
.PHONY : src/embedder.cpp.s

src/import.o: src/import.cpp.o
.PHONY : src/import.o

# target to build an object file
src/import.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/import.cpp.o
.PHONY : src/import.cpp.o

src/import.i: src/import.cpp.i
.PHONY : src/import.i

# target to preprocess a source file
src/import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/import.cpp.i
.PHONY : src/import.cpp.i

src/import.s: src/import.cpp.s
.PHONY : src/import.s

# target to generate assembly for a file
src/import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/import.cpp.s
.PHONY : src/import.cpp.s

src/inference.o: src/inference.cpp.o
.PHONY : src/inference.o

# target to build an object file
src/inference.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/inference.cpp.o
.PHONY : src/inference.cpp.o

src/inference.i: src/inference.cpp.i
.PHONY : src/inference.i

# target to preprocess a source file
src/inference.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/inference.cpp.i
.PHONY : src/inference.cpp.i

src/inference.s: src/inference.cpp.s
.PHONY : src/inference.s

# target to generate assembly for a file
src/inference.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/inference.cpp.s
.PHONY : src/inference.cpp.s

src/logs.o: src/logs.cpp.o
.PHONY : src/logs.o

# target to build an object file
src/logs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/logs.cpp.o
.PHONY : src/logs.cpp.o

src/logs.i: src/logs.cpp.i
.PHONY : src/logs.i

# target to preprocess a source file
src/logs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/logs.cpp.i
.PHONY : src/logs.cpp.i

src/logs.s: src/logs.cpp.s
.PHONY : src/logs.s

# target to generate assembly for a file
src/logs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/logs.cpp.s
.PHONY : src/logs.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger.dir/build.make CMakeFiles/ragger.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger.dir/build.make CMakeFiles/ragger.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger.dir/build.make CMakeFiles/ragger.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/memory.o: src/memory.cpp.o
.PHONY : src/memory.o

# target to build an object file
src/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/memory.cpp.o
.PHONY : src/memory.cpp.o

src/memory.i: src/memory.cpp.i
.PHONY : src/memory.i

# target to preprocess a source file
src/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/memory.cpp.i
.PHONY : src/memory.cpp.i

src/memory.s: src/memory.cpp.s
.PHONY : src/memory.s

# target to generate assembly for a file
src/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/memory.cpp.s
.PHONY : src/memory.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/sqlite_backend.o: src/sqlite_backend.cpp.o
.PHONY : src/sqlite_backend.o

# target to build an object file
src/sqlite_backend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/sqlite_backend.cpp.o
.PHONY : src/sqlite_backend.cpp.o

src/sqlite_backend.i: src/sqlite_backend.cpp.i
.PHONY : src/sqlite_backend.i

# target to preprocess a source file
src/sqlite_backend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/sqlite_backend.cpp.i
.PHONY : src/sqlite_backend.cpp.i

src/sqlite_backend.s: src/sqlite_backend.cpp.s
.PHONY : src/sqlite_backend.s

# target to generate assembly for a file
src/sqlite_backend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/sqlite_backend.cpp.s
.PHONY : src/sqlite_backend.cpp.s

src/tokenizer_wrapper.o: src/tokenizer_wrapper.cpp.o
.PHONY : src/tokenizer_wrapper.o

# target to build an object file
src/tokenizer_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/tokenizer_wrapper.cpp.o
.PHONY : src/tokenizer_wrapper.cpp.o

src/tokenizer_wrapper.i: src/tokenizer_wrapper.cpp.i
.PHONY : src/tokenizer_wrapper.i

# target to preprocess a source file
src/tokenizer_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/tokenizer_wrapper.cpp.i
.PHONY : src/tokenizer_wrapper.cpp.i

src/tokenizer_wrapper.s: src/tokenizer_wrapper.cpp.s
.PHONY : src/tokenizer_wrapper.s

# target to generate assembly for a file
src/tokenizer_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ragger_core.dir/build.make CMakeFiles/ragger_core.dir/src/tokenizer_wrapper.cpp.s
.PHONY : src/tokenizer_wrapper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... doxygen"
	@echo "... c_lib_po"
	@echo "... ragger"
	@echo "... ragger_core"
	@echo "... sentencepiece-static"
	@echo "... sentencepiece_train-static"
	@echo "... spm_decode"
	@echo "... spm_encode"
	@echo "... spm_export_vocab"
	@echo "... spm_normalize"
	@echo "... spm_train"
	@echo "... test_auth"
	@echo "... test_bm25"
	@echo "... test_client"
	@echo "... test_config"
	@echo "... test_import"
	@echo "... test_server"
	@echo "... test_sqlite_backend"
	@echo "... tokenizers_c"
	@echo "... tokenizers_cpp"
	@echo "... ProgramOptions.o"
	@echo "... ProgramOptions.i"
	@echo "... ProgramOptions.s"
	@echo "... src/api_formats.o"
	@echo "... src/api_formats.i"
	@echo "... src/api_formats.s"
	@echo "... src/auth.o"
	@echo "... src/auth.i"
	@echo "... src/auth.s"
	@echo "... src/bm25.o"
	@echo "... src/bm25.i"
	@echo "... src/bm25.s"
	@echo "... src/chat.o"
	@echo "... src/chat.i"
	@echo "... src/chat.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/embedder.o"
	@echo "... src/embedder.i"
	@echo "... src/embedder.s"
	@echo "... src/import.o"
	@echo "... src/import.i"
	@echo "... src/import.s"
	@echo "... src/inference.o"
	@echo "... src/inference.i"
	@echo "... src/inference.s"
	@echo "... src/logs.o"
	@echo "... src/logs.i"
	@echo "... src/logs.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/memory.o"
	@echo "... src/memory.i"
	@echo "... src/memory.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/sqlite_backend.o"
	@echo "... src/sqlite_backend.i"
	@echo "... src/sqlite_backend.s"
	@echo "... src/tokenizer_wrapper.o"
	@echo "... src/tokenizer_wrapper.i"
	@echo "... src/tokenizer_wrapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

